INSERT INTO ELEMENT1 VALUES (1, 'ATTR2_VALUE1', CURRENT_DATE);
INSERT INTO ELEMENT1 VALUES (2, 'ATTR2_VALUE2', CURRENT_DATE);
INSERT INTO ELEMENT1 VALUES (3, 'ATTR2_VALUE3', CURRENT_DATE);

INSERT INTO ELEMENT2 VALUES (4, 'ATTR5_VALUE1', CURRENT_DATE, 1);
INSERT INTO ELEMENT2 VALUES (5, 'ATTR5_VALUE2', CURRENT_DATE, 2);
INSERT INTO ELEMENT2 VALUES (6, 'ATTR5_VALUE3', CURRENT_DATE, 3);
INSERT INTO ELEMENT2 VALUES (7, 'ATTR5_VALUE4', CURRENT_DATE, 5);
INSERT INTO ELEMENT2 VALUES (8, 'ATTR5_VALUE5', CURRENT_DATE, 8);
INSERT INTO ELEMENT2 VALUES (9, 'ATTR5_VALUE6', CURRENT_DATE, 13);
INSERT INTO ELEMENT2 VALUES (10, 'ATTR5_VALUE7', CURRENT_DATE, 21);
INSERT INTO ELEMENT2 VALUES (11, 'ATTR5_VALUE8', CURRENT_DATE, 34);

INSERT INTO ELEMENT3 VALUES(12, 2);
INSERT INTO ELEMENT3 VALUES(13, 3);
INSERT INTO ELEMENT3 VALUES(14, 5);
INSERT INTO ELEMENT3 VALUES(15, 7);
INSERT INTO ELEMENT3 VALUES(16, 11);