CREATE TABLE ELEMENT1(ATTR1 NUMBER, ATTR2 VARCHAR2(4000), ATTR3 DATE, PRIMARY KEY (ATTR1));
CREATE TABLE ELEMENT2(ATTR4 NUMBER, ATTR5 VARCHAR2(4000), ATTR6 DATE, ATTR7 NUMBER, PRIMARY KEY (ATTR4));
CREATE TABLE ELEMENT3(ATTR8 NUMBER, ATTR9 NUMBER, PRIMARY KEY (ATTR8));